### ISSUE TITLE
Delete unused files

### ISSUE THREAD

**Issue by chenrujun** [spring-guides/gs-spring-boot-for-azure#14]
In my understanding, there files / folders are not used anymore. How about deleting them?

> ![image](https://user-images.githubusercontent.com/13167207/219284784-1255b6f6-4ad6-4cfe-bd03-c8e848f9e393.png)

**Comment by chenrujun** [comment]
Hi, @Buzzardo, could you please check this issue and give your feedback? If you agree, I'm glad to create a PR to do this.

**Comment by Buzzardo** [comment]
TL/DR: You can delete the images, which are unused. The rest have to stay.

The details: Our guides all have the initial and test directories, so we want them for congruency. Also, we can (and usallky do) eventually add an initial project (usually the Spring Boot starter from start.spring.io). We need the Jenkinsfile for our CI process, and we have to have the license file for legal purposes.

**Comment by chenrujun** [comment]
@Buzzardo 

Thanks for the detailed explanation. I created a PR: https://github.com/spring-guides/gs-spring-boot-for-azure/pull/15
Please help to review & merge.

**Comment by chenrujun** [comment]
> We need the Jenkinsfile for our CI process

The CI is not triggered in my created PR, #15 . Is it necessary to make the CI triggered for Pull Requests?

**Comment by robertmcnees** [comment]
Hi @chenrujun. Thanks for the PR. I merged it now and we can close this issue.

A few points in the PR I'd like to comment on as we may come back to it:

First, regarding CI in the comment above, we are moving our CI to in spring-guides to GitHub Actions. That should ensure that builds are run when PRs are submitted.

Second, I looked over the guide and I don't think that the `complete` and `initial` folder structure makes sense here since this guide doesn't instruct the user how to build the code that is in the `complete` folder. Rather than simply deleting the `initial` folder, I'd rather delete both `initial` and `complete` and move the project up a level. We could revisit this in a different PR.
